name: Fork Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0 

      - name: Configure Git
        run: |
          git config user.name "HugoFMiranda"
          git config user.email "hugoeu10@gmail.com"

      - name: Add Upstream Repository and Fetch Changes
        run: |
          git remote add upstream https://github.com/keiyoushi/extensions-source.git
          git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout main
          git merge --ff-only upstream/main || echo "No fast-forward possible, skipping merge"

      - name: Push Changes to Your Fork
        env:
          GH_TOKEN: ${{ secrets.FORK_SYNC_BOT_TOKEN }}
        run: |
          git push https://x-access-token:${GH_TOKEN}@github.com/HugoFMiranda/extensions-source.git main
